-- PostgreSQL Database Schema for Aura Estate (Supabase)
-- Execute this SQL script in your Supabase Project SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. Create Users Table (Synced from Firebase Auth)
CREATE TABLE IF NOT EXISTS public.users (
  id VARCHAR(255) PRIMARY KEY, -- Matches Firebase UID
  email VARCHAR(255) UNIQUE NOT NULL,
  name VARCHAR(255),
  membership_id VARCHAR(50),
  tier VARCHAR(100),
  joined_date VARCHAR(100),
  image TEXT, -- Base64 profile picture string
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Create Properties Table
CREATE TABLE IF NOT EXISTS public.properties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  price NUMERIC NOT NULL,
  beds INT NOT NULL,
  baths NUMERIC NOT NULL,
  sqft INT NOT NULL,
  location VARCHAR(255) NOT NULL,
  type VARCHAR(100) NOT NULL,
  image TEXT NOT NULL,
  tag VARCHAR(100),
  description TEXT,
  amenities TEXT[] NOT NULL DEFAULT '{}',
  owner_email VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Create Favorites Many-to-Many Table
CREATE TABLE IF NOT EXISTS public.favorites (
  user_id VARCHAR(255) REFERENCES public.users(id) ON DELETE CASCADE,
  property_id BIGINT REFERENCES public.properties(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, property_id)
);

-- 4. Create Offers Table
CREATE TABLE IF NOT EXISTS public.offers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id BIGINT REFERENCES public.properties(id) ON DELETE CASCADE,
  property_title VARCHAR(255),
  price NUMERIC NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  notes TEXT,
  status VARCHAR(50) DEFAULT 'Pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 5. Enable Row Level Security (RLS) on all Tables
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.offers ENABLE ROW LEVEL SECURITY;

-- 6. Setup RLS Policies for Client-Side Access (anon / authenticated roles)

-- Properties policies
DROP POLICY IF EXISTS "Allow public read access to properties" ON public.properties;
CREATE POLICY "Allow public read access to properties" ON public.properties
  FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Allow authenticated insert to properties" ON public.properties;
CREATE POLICY "Allow authenticated insert to properties" ON public.properties
  FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated update to properties" ON public.properties;
CREATE POLICY "Allow authenticated update to properties" ON public.properties
  FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated delete to properties" ON public.properties;
CREATE POLICY "Allow authenticated delete to properties" ON public.properties
  FOR DELETE TO anon, authenticated USING (true);

-- Users policies
DROP POLICY IF EXISTS "Allow public read access to users" ON public.users;
CREATE POLICY "Allow public read access to users" ON public.users
  FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Allow public insert on users" ON public.users;
CREATE POLICY "Allow public insert on users" ON public.users
  FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update on users" ON public.users;
CREATE POLICY "Allow public update on users" ON public.users
  FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

-- Favorites policies
DROP POLICY IF EXISTS "Allow public select on favorites" ON public.favorites;
CREATE POLICY "Allow public select on favorites" ON public.favorites
  FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Allow public insert on favorites" ON public.favorites;
CREATE POLICY "Allow public insert on favorites" ON public.favorites
  FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public delete on favorites" ON public.favorites;
CREATE POLICY "Allow public delete on favorites" ON public.favorites
  FOR DELETE TO anon, authenticated USING (true);

-- Offers policies
DROP POLICY IF EXISTS "Allow public select on offers" ON public.offers;
CREATE POLICY "Allow public select on offers" ON public.offers
  FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Allow public insert on offers" ON public.offers;
CREATE POLICY "Allow public insert on offers" ON public.offers
  FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update on offers" ON public.offers;
CREATE POLICY "Allow public update on offers" ON public.offers
  FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

-- 7. Create Messages Table for Buyer/Seller Communication
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_email VARCHAR(255) NOT NULL,
  receiver_email VARCHAR(255) NOT NULL,
  property_id BIGINT REFERENCES public.properties(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Messages policies
DROP POLICY IF EXISTS "Allow public select on messages" ON public.messages;
CREATE POLICY "Allow public select on messages" ON public.messages
  FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Allow public insert on messages" ON public.messages;
CREATE POLICY "Allow public insert on messages" ON public.messages
  FOR INSERT TO anon, authenticated WITH CHECK (true);

-- 8. Create Verification Codes Table for 2FA
CREATE TABLE IF NOT EXISTS public.verification_codes (
  email VARCHAR(255) PRIMARY KEY,
  code VARCHAR(50) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.verification_codes ENABLE ROW LEVEL SECURITY;

-- Verification codes policies
DROP POLICY IF EXISTS "Allow public select on verification_codes" ON public.verification_codes;
CREATE POLICY "Allow public select on verification_codes" ON public.verification_codes
  FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Allow public insert on verification_codes" ON public.verification_codes;
CREATE POLICY "Allow public insert on verification_codes" ON public.verification_codes
  FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update on verification_codes" ON public.verification_codes;
CREATE POLICY "Allow public update on verification_codes" ON public.verification_codes
  FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public delete on verification_codes" ON public.verification_codes;
CREATE POLICY "Allow public delete on verification_codes" ON public.verification_codes
  FOR DELETE TO anon, authenticated USING (true);
